### ISSUE TITLE
MSAL .NET on iOS 13 does not support system browser

### ISSUE THREAD

**Issue by zachgreencbt** [Azure-Samples/active-directory-xamarin-native-v2#84] opened 2019-09-25 02:48 UTC
After upgrading to iOS 13/Xcode 11, AcquireTokenInteractive in this sample is no longer working. An exception is raised on line 38 of MainPage.xaml.cs.

"MSAL.Xamarin.iOS.4.3.1.0.MsalClientException: \n\tErrorCode: authentication_canceled\nMicrosoft.Identity.Client.MsalClientException: User canceled authentication.\n  at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.VerifyAuthorizationResult () [0x000c1] in <f86706856cf54febb6d074d639e8d6db>:0 \n  at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x0018a] in <f86706856cf54febb6d074d639e8d6db>:0 \n  at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken) [0x001d2] in <f86706856cf54febb6d074d639e8d6db>:0 \n  at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync (Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenCommonParameters commonParameters, Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenInteractiveParameters interactiveParameters, System.Threading.CancellationToken cancellationToken) [0x000f2
] in <f86706856cf54febb6d074d639e8d6db>:0 \n  at UserDetailsClient.MainPage.OnSignInSignOut (System.Object sender, System.EventArgs e) [0x0024f] in C:\\Users\\zgreen\\Downloads\\active-directory-xamarin-native-v2-msal3x\\UserDetailsClient\\UserDetailsClient\\MainPage.xaml.cs:38 "

**Comment by uarcho** [comment] 2019-09-25 10:14
Same problem on a custom application, getting the user canceled authentication execption and no popup showed

**Comment by andresbj16** [comment] 2019-09-25 12:31
I am getting the same error in the iOS 13 emulator despite having the latest version of the nuget package (4.4.0)

`AuthenticationHelper.AuthResult = await App.PCA.AcquireTokenInteractive(scopes)
                                                               .WithParentActivityOrWindow(App.AuthUIParent)
                                                               .ExecuteAsync();`

<img width="337" alt="Captura de Pantalla 2019-09-25 a la(s) 7 30 29 a  m" src="https://user-images.githubusercontent.com/25508936/65600796-725f0980-df66-11e9-9956-84fd70450840.png">

**Comment by chrisronburns** [comment] 2019-09-25 14:09
Also experiencing this on iOS13

**Comment by jennyf19** [comment] 2019-09-25 14:37
@zachgreencbt @uarcho @andresbj16 @chrisronburns 
Hello,

Can you please provide the full information of your xamarin.iOS installation, would be good to know if this is happening with a package that support xcode11 or with an older one.

The easiest way to get exact version information:

On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

The Xcode version information will also be helpful since we have had several releases from Apple. (GM, GM2 or Xcode11 final).

**Comment by zachgreencbt** [comment] 2019-09-25 14:41
> @zachgreencbt @uarcho @andresbj16 @chrisronburns
> Hello,
> 
> Can you please provide the full information of your xamarin.iOS installation, would be good to know if this is happening with a package that support xcode11 or with an older one.
> 
> The easiest way to get exact version information:
> 
> On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
> On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
> Then copy/paste the version information (you can use the "Copy Information" button).
> 
> The Xcode version information will also be helpful since we have had several releases from Apple. (GM, GM2 or Xcode11 final).

Microsoft Visual Studio Professional 2019
Version 16.3.0
VisualStudio.16.Release/16.3.0+29318.209
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-20150-13783-AA224
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Application Insights Tools for Visual Studio Package   9.1.00913.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.3.282.33872
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.282.33872
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.282.33872
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.9000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.3.282.33872
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.9000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitFlow.VS.Extension   1.0
Visual Studio extension that integrates GitFlow

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.3.9000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.9000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.9000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20816.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Template Studio   3.4.19254.1
Windows Template Studio quickly builds a UWP app, using a wizard-based UI to turn your needs into a foundation of Windows 10 patterns and best practices.

Xamarin   16.3.0.274 (d16-3@06531f8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.230 (remotes/origin/d16-3-xcode11@bbe518670)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.0.43 (d16-3/8af1ca8)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@7af64d1ebe9
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333


Xamarin.iOS and Xamarin.Mac SDK   13.2.0.42 (5e8a208)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by ChristopherSt-Pierre** [comment] 2019-09-25 15:09
Hi guys!

FYI

I have the problem too.
I just updated my development iPhone to iOS 13 and the same problem occured with my custom application and the application: Active-directory-xamarin-native-v2.

V4.4

**Comment by jennyf19** [comment] 2019-09-25 15:15
@ChristopherSt-Pierre Can you confirm the issue is w/the simulator, or are you seeing it on a device as well? thank you.

**Comment by andresbj16** [comment] 2019-09-25 15:20
> @zachgreencbt @uarcho @andresbj16 @chrisronburns
> Hello,
> 
> Can you please provide the full information of your xamarin.iOS installation, would be good to know if this is happening with a package that support xcode11 or with an older one.
> 
> The easiest way to get exact version information:
> 
> On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
> On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
> Then copy/paste the version information (you can use the "Copy Information" button).
> 
> The Xcode version information will also be helpful since we have had several releases from Apple. (GM, GM2 or Xcode11 final).

Visual Studio Enterprise 2019 for Mac
Version 8.3 (build 1805)
Installation UUID: 0c81f74b-067e-4e52-a203-67ba5242d3de
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000198

Mono Framework MDK
Runtime:
	Mono 6.4.0.198 (2019-06/fe64a4765e6) (64-bit)
	Package version: 604000198

NuGet
Versión: 5.3.0.6192

SDK de .NET Core
SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
Versiones del SDK:
	3.0.100
	2.1.701
SDK de MSBuild: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Versiones de tiempo de ejecución:
	3.0.0
	2.1.13
	2.1.12

Xamarin.Profiler
Versión: 1.6.12.26
Ubicación: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Versión: 11

Apple Developer Tools
Xcode 11.0 (14936)
Build 11A420a

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 13.2.0.42 (Visual Studio Enterprise)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

Xamarin Designer
Version: 16.3.0.230
Hash: bbe518670
Branch: remotes/origin/d16-3-xcode11
Build date: 2019-09-17 18:39:30 UTC

Xamarin.Android
Versión: 10.0.0.43 (Visual Studio Enterprise)
Confirmación: xamarin-android/d16-3/8af1ca8
Android SDK: /Users/aardila/Library/Developer/Xamarin/android-sdk-macosx
	Versiones de Android admitidas:
		8.0 (nivel de API 26)

Versión de SDK Tools: 26.1.1
Versión de las herramientas de plataforma del SDK: 29.0.2
Versión de las herramientas de compilación del SDK: 28.0.3

Información de compilación: 
Mono: mono/mono/2019-06@7af64d1ebe9
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Microsoft Mobile OpenJDK
Java SDK: /Users/aardila/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
El código EPL de Android Designer está disponible EPL:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:42:44 UTC

Android Device Manager
Version: 1.2.0.115
Hash: 724ea69
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:43:06 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 803001805
Git revision: df50511ccb08d4d84a53939f1d7fc0b40cbb0ee1
Build date: 2019-09-20 16:10:55+00
Build branch: release-8.3
Xamarin extensions: da8d448cd65f2cc87c5e6dc7e2c2ca7b96d20c72

Operating System
Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by ChristopherSt-Pierre** [comment] 2019-09-25 15:23
> @ChristopherSt-Pierre Can you confirm the issue is w/the simulator, or are you seeing it on a device as well? thank you.

I confirm that the problem is not only on a simulator because I am able to reproduce the problem on my iPhone 6 iOS 13.

**Comment by andresbj16** [comment] 2019-09-26 13:20
> After upgrading to iOS 13/Xcode 11, AcquireTokenInteractive in this sample is no longer working. An exception is raised on line 38 of MainPage.xaml.cs.
> 
> "MSAL.Xamarin.iOS.4.3.1.0.MsalClientException: \n\tErrorCode: authentication_canceled\nMicrosoft.Identity.Client.MsalClientException: User canceled authentication.\n at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.VerifyAuthorizationResult () [0x000c1] in :0 \n at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x0018a] in :0 \n at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken) [0x001d2] in :0 \n at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync (Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenCommonParameters commonParameters, Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenInteractiveParameters interactiveParameters, System.Threading.CancellationToken cancellationToken) [0x000f2
> ] in :0 \n at UserDetailsClient.MainPage.OnSignInSignOut (System.Object sender, System.EventArgs e) [0x0024f] in C:\Users\zgreen\Downloads\active-directory-xamarin-native-v2-msal3x\UserDetailsClient\UserDetailsClient\MainPage.xaml.cs:38 "

The solution is in this link [https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1399](url)

**Comment by jennyf19** [comment] 2019-10-03 17:10
@zachgreencbt @uarcho @andresbj16 @chrisronburns Please see our [updated documentation here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/iOS-13-issue-with-system-browser-on-MSAL-.NET)

**Comment by jennyf19** [comment] 2019-10-16 00:43
@zachgreencbt @uarcho @andresbj16 @chrisronburns fixed in 4.5 release of MSAL.

**Closed by jennyf19** 2019-10-16 00:43 UTC
Labels: bug, iOS, iOS13

**Comment by Karlitos2312** [comment] 2019-10-21 14:58
I can't update from 4.4 to 4.5 

Failed to add reference. The package 'Microsoft.Identity.Client' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**Comment by jennyf19** [comment] 2019-10-21 19:00
@Karlitos2312 That is an issue w/Visual Studio when VS tries to upgrade the dependency. If you manually update to MSAL4.5 (by editing the csproj and the packages) it will work. The workaround is to move away from packages.config to PackageReference. Similar issue [here](https://github.com/MvvmCross/MvvmCross/issues/3531 ).

**Comment by Karlitos2312** [comment] 2019-10-22 14:03
@jennyf19 Thanks for that - solved the problem.
