### ISSUE TITLE
AcquireTokenSilentAsync Is not working as expected after updating MSAL 2.0.0-preview

### ISSUE THREAD

**Issue by crazynitha** [Azure-Samples/active-directory-xamarin-native-v2#38] opened 2018-08-30 09:52 UTC
I tried to update the below line of code based on the new documentation.

 ```
var authResult = await _authenticationClient.AcquireTokenSilentAsync(
                    Settings.Scopes,
                    _authenticationClient.GetUser(AuthenticatedUser.Id),
                    Settings.B2CAuthority(Settings.DefaultB2CTenant, Settings.DefaultB2CPolicy),
                    true);
```
This is all about calling AcquireTokenSilentAsync() but I am getting the response of **GetAccountsAsync()** always null.

```
IEnumerable<IAccount> accounts = await _authenticationClient.GetAccountsAsync();
IAccount firstAccount = accounts.FirstOrDefault();
var authResult = await _authenticationClient.AcquireTokenSilentAsync(
                    Settings.Scopes,
                    accounts,
                    Settings.B2CAuthority(Settings.DefaultB2CTenant, Settings.DefaultB2CPolicy),
                    true);
```

**Comment by jmprieur** [comment] 2018-08-30 10:34
Thanks for reporting @crazynitha 

This is actually one of the MSALNET 1.0.0-preview [known issues](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/msal-net-2-released#known-issues) and affects 'only' B2C. The explanation and the work around are available in https://aka.ms/msal-net-token-cache-index-keys

Closing this issue as a duplicate of [MSAL.NET #603]() where you can track the issue as this sample (as is) is not affected. 

> The corresponding B2C sample (https://github.com/Azure-Samples/active-directory-b2c-xamarin-native) would be affected, but we did not migrate it to MSAL.NET 1.0.0-preview yet.

**Closed by jmprieur** 2018-08-30 10:34 UTC
Labels: duplicate
